export const agGridVietnamese = {
  // Set Filter
  selectAll: '(Chọn tất cả)',
  selectAllSearchResults: '(Chọn tất cả kết quả tìm kiếm)',
  addCurrentSelectionToFilter: 'Thêm lựa chọn hiện tại vào bộ lọc',
  searchOoo: 'Tìm kiếm...',
  blanks: '(Trống)',
  noMatches: 'Không có kết quả',

  // Number Filter & Text Filter
  filterOoo: 'Lọc...',
  equals: 'Bằng',
  notEqual: 'Không bằng',
  blank: 'Trống',
  notBlank: 'Không trống',
  empty: 'Chọn một',

  // Number Filter
  lessThan: 'Nhỏ hơn',
  greaterThan: 'Lớn hơn',
  lessThanOrEqual: 'Nhỏ hơn hoặc bằng',
  greaterThanOrEqual: 'Lớn hơn hoặc bằng',
  inRange: 'Trong khoảng',
  inRangeStart: 'Từ',
  inRangeEnd: 'Đến',

  // Text Filter
  contains: 'Chứa',
  notContains: 'Không chứa',
  startsWith: 'Bắt đầu với',
  endsWith: 'Kết thúc với',

  // Date Filter
  dateFormatOoo: 'yyyy-mm-dd',

  // Filter Conditions
  andCondition: 'VÀ',
  orCondition: 'HOẶC',

  // Filter Buttons
  applyFilter: 'Áp dụng',
  resetFilter: 'Đặt lại',
  clearFilter: 'Xóa',
  cancelFilter: 'Hủy',

  // Filter Titles
  textFilter: 'Lọc văn bản',
  numberFilter: 'Lọc số',
  dateFilter: 'Lọc ngày',
  setFilter: 'Lọc tập hợp',

  // Group Column Filter
  groupFilterSelect: 'Chọn trường:',

  // Advanced Filter
  advancedFilterContains: 'chứa',
  advancedFilterNotContains: 'không chứa',
  advancedFilterTextEquals: 'bằng',
  advancedFilterTextNotEqual: 'không bằng',
  advancedFilterStartsWith: 'bắt đầu với',
  advancedFilterEndsWith: 'kết thúc với',
  advancedFilterBlank: 'trống',
  advancedFilterNotBlank: 'không trống',
  advancedFilterEquals: '=',
  advancedFilterNotEqual: '!=',
  advancedFilterGreaterThan: '>',
  advancedFilterGreaterThanOrEqual: '>=',
  advancedFilterLessThan: '<',
  advancedFilterLessThanOrEqual: '<=',
  advancedFilterTrue: 'đúng',
  advancedFilterFalse: 'sai',
  advancedFilterAnd: 'VÀ',
  advancedFilterOr: 'HOẶC',
  advancedFilterApply: 'Áp dụng',
  advancedFilterBuilder: 'Trình tạo',
  advancedFilterValidationMissingColumn: 'Thiếu cột',
  advancedFilterValidationMissingOption: 'Thiếu tùy chọn',
  advancedFilterValidationMissingValue: 'Thiếu giá trị',
  advancedFilterValidationInvalidColumn: 'Không tìm thấy cột',
  advancedFilterValidationInvalidOption: 'Không tìm thấy tùy chọn',
  advancedFilterValidationMissingQuote: 'Giá trị thiếu dấu ngoặc kép kết thúc',
  advancedFilterValidationNotANumber: 'Giá trị không phải là số',
  advancedFilterValidationInvalidDate: 'Giá trị không phải là ngày hợp lệ',
  advancedFilterValidationMissingCondition: 'Thiếu điều kiện',
  advancedFilterValidationJoinOperatorMismatch: 'Toán tử nối trong một điều kiện phải giống nhau',
  advancedFilterValidationInvalidJoinOperator: 'Không tìm thấy toán tử nối',
  advancedFilterValidationMissingEndBracket: 'Thiếu dấu ngoặc kết thúc',
  advancedFilterValidationExtraEndBracket: 'Quá nhiều dấu ngoặc kết thúc',
  advancedFilterValidationMessage: 'Biểu thức có lỗi. ${variable} - ${variable}.',
  advancedFilterValidationMessageAtEnd: 'Biểu thức có lỗi. ${variable} ở cuối biểu thức.',
  advancedFilterBuilderTitle: 'Bộ lọc nâng cao',
  advancedFilterBuilderApply: 'Áp dụng',
  advancedFilterBuilderCancel: 'Hủy',
  advancedFilterBuilderAddButtonTooltip: 'Thêm bộ lọc hoặc nhóm',
  advancedFilterBuilderRemoveButtonTooltip: 'Xóa',
  advancedFilterBuilderMoveUpButtonTooltip: 'Di chuyển lên',
  advancedFilterBuilderMoveDownButtonTooltip: 'Di chuyển xuống',
  advancedFilterBuilderAddJoin: 'Thêm nhóm',
  advancedFilterBuilderAddCondition: 'Thêm bộ lọc',
  advancedFilterBuilderSelectColumn: 'Chọn cột',
  advancedFilterBuilderSelectOption: 'Chọn tùy chọn',
  advancedFilterBuilderEnterValue: 'Nhập giá trị...',
  advancedFilterBuilderValidationAlreadyApplied: 'Bộ lọc hiện tại đã được áp dụng.',
  advancedFilterBuilderValidationIncomplete: 'Không phải tất cả điều kiện đều hoàn chỉnh.',
  advancedFilterBuilderValidationSelectColumn: 'Phải chọn một cột.',
  advancedFilterBuilderValidationSelectOption: 'Phải chọn một tùy chọn.',
  advancedFilterBuilderValidationEnterValue: 'Phải nhập một giá trị.',

  // Side Bar
  columns: 'Cột',
  filters: 'Bộ lọc',

  // columns tool panel
  pivotMode: 'Chế độ Pivot',
  groups: 'Nhóm hàng',
  rowGroupColumnsEmptyMessage: 'Kéo vào đây để đặt nhóm hàng',
  values: 'Giá trị',
  valueColumnsEmptyMessage: 'Kéo vào đây để tổng hợp',
  pivots: 'Nhãn cột',
  pivotColumnsEmptyMessage: 'Kéo vào đây để đặt nhãn cột',

  // Header of the Default Group Column
  group: 'Nhóm',

  // Row Drag
  rowDragRow: 'hàng',
  rowDragRows: 'hàng',

  // Other
  loadingOoo: 'Đang tải...',
  loadingError: 'LỖI',
  noRowsToShow: 'Không có dữ liệu',
  enabled: 'Bật',

  // Menu
  pinColumn: 'Ghim cột',
  pinLeft: 'Ghim trái',
  pinRight: 'Ghim phải',
  noPin: 'Không ghim',
  valueAggregation: 'Tổng hợp giá trị',
  noAggregation: 'Không',
  autosizeThisColumn: 'Tự động điều chỉnh cột này',
  autosizeAllColumns: 'Tự động điều chỉnh tất cả cột',
  groupBy: 'Nhóm theo',
  ungroupBy: 'Bỏ nhóm theo',
  ungroupAll: 'Bỏ nhóm tất cả',
  addToValues: 'Thêm ${variable} vào giá trị',
  removeFromValues: 'Xóa ${variable} khỏi giá trị',
  addToLabels: 'Thêm ${variable} vào nhãn',
  removeFromLabels: 'Xóa ${variable} khỏi nhãn',
  resetColumns: 'Đặt lại cột',
  expandAll: 'Mở rộng tất cả nhóm hàng',
  collapseAll: 'Đóng tất cả nhóm hàng',
  copy: 'Sao chép',
  ctrlC: 'Ctrl+C',
  ctrlX: 'Ctrl+X',
  copyWithHeaders: 'Sao chép với tiêu đề',
  copyWithGroupHeaders: 'Sao chép với tiêu đề nhóm',
  cut: 'Cắt',
  paste: 'Dán',
  ctrlV: 'Ctrl+V',
  export: 'Xuất',
  csvExport: 'Xuất CSV',
  excelExport: 'Xuất Excel',

  // Enterprise Menu Aggregation and Status Bar
  sum: 'Tổng',
  first: 'Đầu tiên',
  last: 'Cuối cùng',
  min: 'Nhỏ nhất',
  max: 'Lớn nhất',
  none: 'Không',
  count: 'Đếm',
  avg: 'Trung bình',
  filteredRows: 'Đã lọc',
  selectedRows: 'Đã chọn',
  totalRows: 'Tổng số hàng',
  totalAndFilteredRows: 'Hàng',
  more: 'Thêm',
  to: 'đến',
  of: 'của',
  page: 'Trang',
  pageLastRowUnknown: '?',
  nextPage: 'Trang sau',
  lastPage: 'Trang cuối',
  firstPage: 'Trang đầu',
  previousPage: 'Trang trước',
  pageSizeSelectorLabel: 'Kích thước trang:',

  // Pivoting
  pivotColumnGroupTotals: 'Tổng',

  // Enterprise Menu (Charts)
  pivotChartAndPivotMode: 'Biểu đồ Pivot & Chế độ Pivot',
  pivotChart: 'Biểu đồ Pivot',
  chartRange: 'Phạm vi biểu đồ',

  columnChart: 'Cột',
  groupedColumn: 'Nhóm',
  stackedColumn: 'Xếp chồng',
  normalizedColumn: '100% xếp chồng',

  barChart: 'Thanh',
  groupedBar: 'Nhóm',
  stackedBar: 'Xếp chồng',
  normalizedBar: '100% xếp chồng',

  pieChart: 'Tròn',
  pie: 'Tròn',
  donut: 'Vòng',

  line: 'Đường',

  xyChart: 'X Y (Phân tán)',
  scatter: 'Phân tán',
  bubble: 'Bong bóng',

  areaChart: 'Vùng',
  area: 'Vùng',
  stackedArea: 'Xếp chồng',
  normalizedArea: '100% xếp chồng',

  histogramChart: 'Biểu đồ tần suất',
  histogramFrequency: 'Tần suất',

  combinationChart: 'Kết hợp',
  columnLineCombo: 'Cột & Đường',
  AreaColumnCombo: 'Vùng & Cột',

  // Charts
  pivotChartTitle: 'Biểu đồ Pivot',
  rangeChartTitle: 'Biểu đồ phạm vi',
  settings: 'Cài đặt',
  data: 'Dữ liệu',
  format: 'Định dạng',
  categories: 'Danh mục',
  defaultCategory: '(Không)',
  series: 'Chuỗi',
  xyValues: 'Giá trị X Y',
  paired: 'Chế độ ghép đôi',
  axis: 'Trục',
  navigator: 'Điều hướng',
  color: 'Màu',
  thickness: 'Độ dày',
  xType: 'Loại X',
  automatic: 'Tự động',
  category: 'Danh mục',
  number: 'Số',
  time: 'Thời gian',
  autoRotate: 'Tự động xoay',
  xRotation: 'Xoay X',
  yRotation: 'Xoay Y',
  ticks: 'Vạch',
  width: 'Độ rộng',
  height: 'Độ cao',
  length: 'Độ dài',
  padding: 'Đệm',
  spacing: 'Khoảng cách',
  chart: 'Biểu đồ',
  title: 'Tiêu đề',
  titlePlaceholder: 'Tiêu đề biểu đồ - nhấp đúp để chỉnh sửa',
  background: 'Nền',
  font: 'Phông chữ',
  top: 'Trên',
  right: 'Phải',
  bottom: 'Dưới',
  left: 'Trái',
  labels: 'Nhãn',
  size: 'Kích thước',
  minSize: 'Kích thước tối thiểu',
  maxSize: 'Kích thước tối đa',
  legend: 'Chú giải',
  position: 'Vị trí',
  markerSize: 'Kích thước điểm đánh dấu',
  markerStroke: 'Nét điểm đánh dấu',
  markerPadding: 'Đệm điểm đánh dấu',
  itemSpacing: 'Khoảng cách mục',
  itemPaddingX: 'Đệm X mục',
  itemPaddingY: 'Đệm Y mục',
  layoutHorizontalSpacing: 'Khoảng cách ngang',
  layoutVerticalSpacing: 'Khoảng cách dọc',
  strokeWidth: 'Độ rộng nét',
  lineDash: 'Nét đứt',
  offset: 'Độ lệch',
  offsets: 'Độ lệch',
  tooltips: 'Chú giải công cụ',
  callout: 'Chú thích',
  markers: 'Điểm đánh dấu',
  shadow: 'Bóng',
  blur: 'Mờ',
  xOffset: 'Độ lệch X',
  yOffset: 'Độ lệch Y',
  lineWidth: 'Độ rộng đường',
  normal: 'Bình thường',
  bold: 'Đậm',
  italic: 'Nghiêng',
  boldItalic: 'Đậm nghiêng',
  predefined: 'Định sẵn',
  fillOpacity: 'Độ mờ đục tô',
  strokeOpacity: 'Độ mờ đục nét',
  histogramBinCount: 'Số lượng bin',
  columnGroup: 'Cột',
  barGroup: 'Thanh',
  pieGroup: 'Tròn',
  lineGroup: 'Đường',
  scatterGroup: 'X Y (Phân tán)',
  areaGroup: 'Vùng',
  histogramGroup: 'Biểu đồ tần suất',
  combinationGroup: 'Kết hợp',
  groupedColumnTooltip: 'Nhóm',
  stackedColumnTooltip: 'Xếp chồng',
  normalizedColumnTooltip: '100% xếp chồng',
  groupedBarTooltip: 'Nhóm',
  stackedBarTooltip: 'Xếp chồng',
  normalizedBarTooltip: '100% xếp chồng',
  pieTooltip: 'Tròn',
  donutTooltip: 'Vòng',
  lineTooltip: 'Đường',
  groupedAreaTooltip: 'Vùng',
  stackedAreaTooltip: 'Xếp chồng',
  normalizedAreaTooltip: '100% xếp chồng',
  scatterTooltip: 'Phân tán',
  bubbleTooltip: 'Bong bóng',
  histogramTooltip: 'Biểu đồ tần suất',
  columnLineComboTooltip: 'Cột & Đường',
  areaColumnComboTooltip: 'Vùng & Cột',
  customComboTooltip: 'Kết hợp tùy chỉnh',
  noDataToChart: 'Không có dữ liệu để tạo biểu đồ.',
  pivotChartRequiresPivotMode: 'Biểu đồ Pivot yêu cầu bật Chế độ Pivot.',
  chartSettingsToolbarTooltip: 'Menu',
  chartLinkToolbarTooltip: 'Liên kết với lưới',
  chartUnlinkToolbarTooltip: 'Hủy liên kết khỏi lưới',
  chartDownloadToolbarTooltip: 'Tải xuống biểu đồ',
  seriesChartType: 'Loại biểu đồ chuỗi',
  seriesType: 'Loại chuỗi',
  secondaryAxis: 'Trục phụ',

  // ARIA
  ariaAdvancedFilterBuilderItem: '${variable}. Cấp ${variable}. Nhấn ENTER để chỉnh sửa.',
  ariaAdvancedFilterBuilderItemValidation:
    '${variable}. Cấp ${variable}. ${variable} Nhấn ENTER để chỉnh sửa.',
  ariaAdvancedFilterBuilderList: 'Danh sách trình tạo bộ lọc nâng cao',
  ariaAdvancedFilterBuilderFilterItem: 'Điều kiện lọc',
  ariaAdvancedFilterBuilderGroupItem: 'Nhóm lọc',
  ariaAdvancedFilterBuilderColumn: 'Cột',
  ariaAdvancedFilterBuilderOption: 'Tùy chọn',
  ariaAdvancedFilterBuilderValueP: 'Giá trị',
  ariaAdvancedFilterBuilderJoinOperator: 'Toán tử nối',
  ariaAdvancedFilterInput: 'Đầu vào bộ lọc nâng cao',
  ariaChecked: 'đã chọn',
  ariaColumn: 'Cột',
  ariaColumnGroup: 'Nhóm cột',
  ariaColumnList: 'Danh sách cột',
  ariaColumnSelectAll: 'Chuyển đổi chọn tất cả cột',
  ariaDateFilterInput: 'Đầu vào bộ lọc ngày',
  ariaDefaultListName: 'Danh sách',
  ariaFilterColumnsInput: 'Đầu vào lọc cột',
  ariaFilterFromValue: 'Lọc từ giá trị',
  ariaFilterInput: 'Đầu vào bộ lọc',
  ariaFilterList: 'Danh sách bộ lọc',
  ariaFilterToValue: 'Lọc đến giá trị',
  ariaFilterValue: 'Giá trị lọc',
  ariaFilterMenuOpen: 'Mở menu lọc',
  ariaFilteringOperator: 'Toán tử lọc',
  ariaHidden: 'ẩn',
  ariaIndeterminate: 'không xác định',
  ariaInputEditor: 'Trình chỉnh sửa đầu vào',
  ariaMenuColumn: 'Nhấn ALT xuống để mở menu cột',
  ariaFilterColumn: 'Nhấn CTRL ENTER để mở bộ lọc',
  ariaRowDeselect: 'Nhấn SPACE để bỏ chọn hàng này',
  ariaRowSelectAll: 'Nhấn Space để chuyển đổi chọn tất cả hàng',
  ariaRowToggleSelection: 'Nhấn Space để chuyển đổi chọn hàng',
  ariaRowSelect: 'Nhấn SPACE để chọn hàng này',
  ariaSearch: 'Tìm kiếm',
  ariaSortableColumn: 'Nhấn ENTER để sắp xếp',
  ariaToggleVisibility: 'Nhấn SPACE để chuyển đổi hiển thị',
  ariaToggleCellValue: 'Nhấn SPACE để chuyển đổi giá trị ô',
  ariaUnchecked: 'chưa chọn',
  ariaVisible: 'hiển thị',
  ariaSearchFilterValues: 'Tìm kiếm giá trị lọc',
  ariaPageSizeSelectorLabel: 'Kích thước trang',
  ariaChartMenuClose: 'Đóng menu chỉnh sửa biểu đồ',
  ariaChartSelected: 'Đã chọn',
  ariaSkeletonCellLoadingFailed: 'Tải hàng thất bại',
  ariaSkeletonCellLoading: 'Dữ liệu hàng đang tải',

  // ARIA Labels for Drop Zones
  ariaRowGroupDropZonePanelLabel: 'Nhóm hàng',
  ariaValuesDropZonePanelLabel: 'Giá trị',
  ariaPivotDropZonePanelLabel: 'Nhãn cột',
  ariaDropZoneColumnComponentDescription: 'Nhấn DELETE để xóa',
  ariaDropZoneColumnValueItemDescription: 'Nhấn ENTER để thay đổi loại tổng hợp',
  ariaDropZoneColumnGroupItemDescription: 'Nhấn ENTER để sắp xếp',

  // used for aggregate drop zone, format: {aggregation}{ariaDropZoneColumnComponentAggFuncSeparator}{column name}
  ariaDropZoneColumnComponentAggFuncSeparator: ' của ',
  ariaDropZoneColumnComponentSortAscending: 'tăng dần',
  ariaDropZoneColumnComponentSortDescending: 'giảm dần',

  // ARIA Labels for Dialogs
  ariaLabelColumnMenu: 'Menu cột',
  ariaLabelColumnFilter: 'Bộ lọc cột',
  ariaLabelCellEditor: 'Trình chỉnh sửa ô',
  ariaLabelDialog: 'Hộp thoại',
  ariaLabelSelectField: 'Chọn trường',
  ariaLabelRichSelectField: 'Trường chọn phong phú',
  ariaLabelTooltip: 'Chú giải công cụ',
  ariaLabelContextMenu: 'Menu ngữ cảnh',
  ariaLabelSubMenu: 'Menu phụ',
  ariaLabelAggregationFunction: 'Hàm tổng hợp',
  ariaLabelAdvancedFilterAutocomplete: 'Tự động hoàn thành bộ lọc nâng cao',
  ariaLabelAdvancedFilterBuilderAddField: 'Thêm trường trình tạo bộ lọc nâng cao',
  ariaLabelAdvancedFilterBuilderColumnSelectField: 'Trường chọn cột trình tạo bộ lọc nâng cao',
  ariaLabelAdvancedFilterBuilderOptionSelectField: 'Trường chọn tùy chọn trình tạo bộ lọc nâng cao',
  ariaLabelAdvancedFilterBuilderJoinSelectField: 'Trường chọn toán tử nối trình tạo bộ lọc nâng cao',

  // ARIA Labels for the Side Bar
  ariaColumnPanelList: 'Danh sách cột',
  ariaFilterPanelList: 'Danh sách bộ lọc',

  // Number Format (Status Bar, Pagination Panel)
  thousandSeparator: '.',
  decimalSeparator: ',',

  // Data types
  true: 'Đúng',
  false: 'Sai',
  invalidDate: 'Ngày không hợp lệ',
  invalidNumber: 'Số không hợp lệ',
  january: 'Tháng 1',
  february: 'Tháng 2',
  march: 'Tháng 3',
  april: 'Tháng 4',
  may: 'Tháng 5',
  june: 'Tháng 6',
  july: 'Tháng 7',
  august: 'Tháng 8',
  september: 'Tháng 9',
  october: 'Tháng 10',
  november: 'Tháng 11',
  december: 'Tháng 12',

  // Time formats
  timeFormatSlashesDDMMYYYY: 'DD/MM/YYYY',
  timeFormatSlashesMMDDYYYY: 'MM/DD/YYYY',
  timeFormatSlashesDDMMYY: 'DD/MM/YY',
  timeFormatSlashesMMDDYY: 'MM/DD/YY',
  timeFormatDotsDDMYY: 'DD.M.YY',
  timeFormatDotsMDDYY: 'M.DD.YY',
  timeFormatDashesYYYYMMDD: 'YYYY-MM-DD',
  timeFormatSpacesDDMMMMYYYY: 'DD MMMM YYYY',
  timeFormatHHMMSS: 'HH:MM:SS',
  timeFormatHHMMSSAmPm: 'HH:MM:SS SA/CH',
}
